### ISSUE TITLE
Add image compression (lossy & lossless) support

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-image-tools#18] opened 2018-05-02 11:17 UTC

**Comment by andrey-ciclicci** [comment] 2018-08-17 15:37
Looks like a duplicate of #22

**Comment by asvishnyakov** [comment] 2018-08-20 08:03
@tatarincev Be careful: it's not about jpeg, png may be compressed lossless too

**Comment by andrey-ciclicci** [comment] 2018-08-20 12:07
Here is a PNG compression chart using a sample photo: 
![image](https://user-images.githubusercontent.com/42266842/44339433-015b4180-a48a-11e8-9c3f-1b9c3b0f2327.png)
It appears that the difference between minimal and maximal compression values makes ~7% of image size (2.01MB vs 2.16MB). Taking into the account the performance impact for maximum compression rate we could leave the default one as a good balance point between size and speed.

**Comment by andrey-ciclicci** [comment] 2018-08-29 11:44
Built-in encoders support only BMP, GIF, JPEG, PNG and TIFF formats [(link)](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.fromfile?redirectedfrom=MSDN&view=netframework-4.7.2#System_Drawing_Image_FromFile_System_String_)

Different programs can produce different results on the same PNG file based on the encoding stage used [()](https://stackoverflow.com/a/8632149) but the compression rate is almost unpredictable for different images, optimizers work in a brute-force way.

For a typical catalog PNG image the compression difference barely exceeds 15-30 KB per file, based on experiments. Also I haven't found any information yet on how to change the default compression level in built-in encoder.

**Closed** 2018-09-10 07:34 UTC
Labels: client request, enhancement
